export const SET_SINGER = 'SET_SINGER'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_SEARCH_STATUS = 'SET_SEARCH_STATUS'

export const SET_WATCH_LIKE = 'SET_WATCH_LIKE'

export const SET_PLAY_LIST_ROUTER = 'SET_PLAY_LIST_ROUTER'

export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY'

export const SET_USER = 'SET_USER'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'
