export const SET_SINGER = 'SET_SINGER'

export const SET_USER = 'SET_USER'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_SEARCH_STATUS = 'SET_SEARCH_STATUS'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'
